apiVersion: v1
kind: Service
metadata:
  name: my-front-end-service-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: my-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}

