apiVersion: v1
kind: Service
metadata:
  name: my-front-end-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}

