apiVersion: v1
kind: Service
metadata:
  name: my-back-end-service
  labels:
    app: my-backend
spec:
  type: ClusterIP
  selector:
    app: my-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

